### ISSUE TITLE
When is the next release?

### ISSUE THREAD

**Issue by joowani** [jazzband/django-silk#636] opened 2022-12-28 03:50 UTC
Hello, when will you be releasing the next version on PyPI? Been waiting for commit e814d0c520165eb2cb0630a6f283b8ed0b803c6d for a couple of months now. Thank you.

**Comment by albertyw** [comment] 2023-01-07 04:45
Duplicate of #622.

Probably sometime this week or whenever some of the pending pull requests get merged.

**Closed by albertyw** 2023-01-07 04:45 UTC
