### ISSUE TITLE
Feature to profile Crons commands?

### ISSUE THREAD

**Issue by bruno911** [jazzband/django-silk#608] opened 2022-10-19 15:04 UTC
Hi,

I was wondering if there is a feature to profile crons, or if there is a way to do it.

I noticed silk will only work when there is a request generated by a view, so is there a way to override this file so that it will also work on crons?

We love silk but we have some long running crons that we would like to debug in production.

If is not possible, could I get some minor directions on how it could be implemented so that I can create a pull request for it?

I guess after this is implemented, it will not be too hard to do a similar thing for celery, I will be happy to create both pull requests if someone could tell me more and less how you would like it to be done so that the pull request gets approved and merged.

Thank you! Congrats for the library it is really useful!

**Comment by SebCorbin** [comment] 2022-10-27 10:21
Duplicate of #593

**Closed by SebCorbin** 2022-10-27 10:21 UTC
Labels: duplicate, feature

**Comment by OscarVanL** [comment] 2024-03-24 08:53
FYI I found [this GitHub gist](https://gist.github.com/mh-keshavarz/eb966905428ef9017ee1ff7d25518bba) that you can use to run django-silk against arbitrary functions not wrapped in APIs. This was a good-enough workaround for me to debug some performance challenges, although it would be fantastic to see something supported by django-silk in the future.
