### ISSUE TITLE
No cPython profiler dump visible

### ISSUE THREAD

**Issue by fuwaneko** [jazzband/django-silk#181] opened 2017-06-13 14:37 UTC
PR #171 introduced a [regression](https://github.com/django-silk/silk/pull/171/files#diff-96ac7cabc6e601b3d8eb08f0f7bcac80L256). Below Silk Profiler should be cPython profiler dump. It is stored in the DB but isn't there in the template anymore. I wonder why nobody noticed this.

Current state:
![image](https://user-images.githubusercontent.com/34433/27087319-430d3474-5087-11e7-9a82-8b07c6bb8c12.png)

Expected state:
![image](https://user-images.githubusercontent.com/34433/27087859-b89c7244-5088-11e7-8dc0-4af363f9585f.png)

**Comment by avelis** [comment] 2017-06-13 20:04
@fuwaneko Thanks for bringing this to my attention. If you have time to make a PR to fix the regression I happily encourage it. Otherwise I would have to get to this at a later time when I work on it.

**Comment by SebCorbin** [comment] 2022-10-27 20:56
This seems to be fixed, closing

**Closed by SebCorbin** 2022-10-27 20:56 UTC
Labels: bug, help wanted
